server:
  port: 8082
  servlet:
      context-path: /wzool
      session:
        timeout: 3600s
spring:
  datasource:
    name: WZool
    url: jdbc:mysql://127.0.0.1:3306/zool?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initial-size: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
     database: 0
     host: 127.0.0.1
     password: root
     port: 6379
     timeout: 30000
     exprie: 1000
     jedis:
       pool:
             max-idle: 500
             min-idle: 50
             max-active: 2000
             max-wait: 1000ms

logging:
  level:
    org.springframework: DEBUG
    com.fworldcodez.wzool.dao: INFO
    com.fworldcodez.wzool.controller: DEBUG
#    com.fworldcodez.wzool.cofig: info
#    org.spring.springboot.dao=DEBUG
    org.mybatis.com.*: info
  file: logs/WZool.log
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.fworldcodez.wzool.pojo

myConfig:
  sessionInfo: sessionInfo
  sessionPrefix: SHIRO_SESSION_ID
  imagePath: /page/image/

